version: "3.8"

services:

  server:
    image: go-clean-architecture
    container_name: "go-clean-architecture"
    build:
      context: ../.
      dockerfile: build/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4.2
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=testdb
    volumes:
      - ../.data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null